[api]
listen="0.0.0.0:11360"

[rpc]
host="127.0.0.1:1234"
tls=false
admin="admin"
password="123"

[sync]
# start sync from block order
start=503042
confirmations=5
# synchronized address list
address=[

]