[api]
listen="0.0.0.0:11360"

[rpc]
host="127.0.0.1:1234"
tls=false
admin="admin"
password="123"

[sync]
# start sync from block order
start=0
# synchronized address list
address=[
    "XmkgU8m4G2GwRjz6rEVskG9HAabT5uUS8Fy","XmjA6CZvLPS3tUeveJi6Tw1Fd7MEq45S93K","Xmii5LiL1MaixQ7Dgi7gbC7Kq1iDBTRS9PW"
]