[api]
listen="0.0.0.0:11360"

[rpc]
host="127.0.0.1"
tls=false
admin="test"
password="test"

[sync]
# start sync from block order
start=0
confirmations=5
# synchronized address list
address=[
    "XXXXXXXXXXXXXXXXXXXX"
]